;; Enable smooth scroll mode
(smooth-scroll-mode t)

;; Make these numbers large to avoid the "animation" of scrolling
(setq smooth-scroll/vscroll-step-size 100)
(setq smooth-scroll/hscroll-step-size 100)

;; Setup mouse wheel binding
(defun my-scroll-up-single () (interactive) (scroll-down-1 1))
(defun my-scroll-up-double () (interactive) (scroll-down-1 5))
(defun my-scroll-up-triple () (interactive) (scroll-down-1 10))
(defun my-scroll-down-single () (interactive) (scroll-up-1 1))
(defun my-scroll-down-double () (interactive) (scroll-up-1 5))
(defun my-scroll-down-triple () (interactive) (scroll-up-1 10))
(defun my-scroll-left-single () (interactive) (scroll-right-1 1))
(defun my-scroll-left-double () (interactive) (scroll-right-1 5))
(defun my-scroll-left-triple () (interactive) (scroll-right-1 10))
(defun my-scroll-right-single () (interactive) (scroll-left-1 1))
(defun my-scroll-right-double () (interactive) (scroll-left-1 5))
(defun my-scroll-right-triple () (interactive) (scroll-left-1 10))

(global-set-key [wheel-up] 'my-scroll-up-single)
(global-set-key [double-wheel-up] 'my-scroll-up-double)
(global-set-key [triple-wheel-up] 'my-scroll-up-triple)
(global-set-key [wheel-down] 'my-scroll-down-single)
(global-set-key [double-wheel-down] 'my-scroll-down-double)
(global-set-key [triple-wheel-down] 'my-scroll-down-triple)
(global-set-key [wheel-right] 'my-scroll-right-single)
(global-set-key [double-wheel-right] 'my-scroll-right-double)
(global-set-key [triple-wheel-right] 'my-scroll-right-triple)
(global-set-key [wheel-left] 'my-scroll-left-single)
(global-set-key [double-wheel-left] 'my-scroll-left-double)
(global-set-key [triple-wheel-left] 'my-scroll-left-triple)
(global-set-key [S-wheel-right] 'my-scroll-right-single)
(global-set-key [S-double-wheel-right] 'my-scroll-right-double)
(global-set-key [S-triple-wheel-right] 'my-scroll-right-triple)
(global-set-key [S-wheel-left] 'my-scroll-left-single)
(global-set-key [S-double-wheel-left] 'my-scroll-left-double)
(global-set-key [S-triple-wheel-left] 'my-scroll-left-triple)
