" Highlight current line
set cursorline

" Disable GUI scrollbar
set guioptions-=L
set guioptions-=T
set guioptions-=r

" Disable BOM
set encoding=utf-8 nobomb

" Remember histories and marks for background buffers
set hidden
set history=1000

" Always show status line
set laststatus=2

" Use extended regexp
set magic

" Disable line wrap
set nowrap

" Show line number
set number

" Show filename in title bar
set title

" Set column guide
set colorcolumn=100

" Set font
set guifont=Source\ Code\ Pro\ for\ Powerline:h14

" Ignore patterns
set wildignore+=*.jpg,*.jpeg,*.gif,*.png,*.gif,*.psd
set wildignore+=*.o,*.obj,*.min.js,*.sassc,*.scssc,*.log
set wildignore+=*~,.DS_Store,*.cache,*.tmp,*.swp
set wildignore+=*/.svn/*,*/.git/*,*/.hg/*
set wildignore+=*/tmp/*,*/log/*,*/build/*

" Use 2 spaces for tab (run :retab on existing files to convert tabs to spaces)
set tabstop=2
set shiftwidth=2
set expandtab

" Indent
set autoindent
set smartindent

" Omni-Complete
set ofu=syntaxcomplete#Complete
set completeopt=longest,menuone

" Local directories
set backupdir=$HOME/.vim/backups
set directory=$HOME/.vim/swaps
set undodir=$HOME/.vim/undo

" Search
set hlsearch
set ignorecase
set smartcase " Don't ignore case if searching with upper case letter
set incsearch
set wrapscan

" Scroling edge offset
set scrolloff=3
set sidescrolloff=3

" New window
set splitbelow
set splitright

" Mouse
set mouse=a " Mouse in all mods
set ttymouse=xterm

" Bell
set noerrorbells
set visualbell

" Command mode completion
set wildmenu
set wildmode=list:longest

" Filetype associations
au BufRead,BufNewFile *.md set filetype=markdown

" Create .netrwhist in $HOME
let g:netrw_home=$HOME

" Disable folding
set nofoldenable
au BufRead,BufNewFile * set nofoldenable

" Misc. configs
set nocompatible
set autoread
set ttyfast
syntax on
filetype plugin indent on
colorscheme desert
highlight ColorColumn ctermbg=DarkGray

" Setup bundles managed by Vundle
so ~/.vim/vimrc.vundle

" Setup key bindings
so ~/.vim/vimrc.bindings

