set nocompatible

" Disable swap files
set noswapfile
set nobackup
set nowb

" Disable GUI scrollbar
set guioptions-=L
set guioptions-=T
set guioptions-=r

" Disable GUI tabs
set guioptions-=e

" Disable BOM
set encoding=utf-8 nobomb

" Disable code folding
set nofoldenable

" Remember histories and marks for background buffers
set hidden
set history=1000

" Allow backspace in insert mode
set backspace=indent,eol,start

" Highlight current line
set cursorline

" Always ues system clipbaord by default
set clipboard=unnamed,unnamedplus

" Always show status line
set laststatus=2

" Use extended regexp
set magic

" Disable line wrap
set nowrap

" Show line number
set number

" Show filename in title bar
set title

" Set column guide
set colorcolumn=100

" Set font
set guifont=Monaco:h12

" Set terminal color
set t_Co=256

" Auto reload when files are changed
set autoread

" Ignore patterns
set wildignore+=*.jpg,*.jpeg,*.gif,*.png,*.gif,*.psd
set wildignore+=*.o,*.obj,*.min.js,*.min.css,*.sassc,*.scssc,*.elc,*.log,*.jar
set wildignore+=*~*.cache,*.tmp,*.swp
set wildignore+=.DS_Store,.AppleDouble,.Spotlight-V100,.Trashes
set wildignore+=*/.svn/*,*/.git/*,*/.hg/*
set wildignore+=*/tmp,*/log,*/build,*/buildSrc
set wildignore+=*/node_modules
set wildignore+=*/frontend/coverage
set wildignore+=*/js-dist-*
set wildignore+=*/src/main/webapp/gen

" Use 2 spaces for tab (run :retab on existing files to convert tabs to spaces)
set tabstop=2
set shiftwidth=2
set expandtab

" Indent
set autoindent
set smartindent

" Omni-Complete
set ofu=syntaxcomplete#Complete
set completeopt=longest,menuone

" Local directories
set backupdir=$HOME/.vim/backups
set directory=$HOME/.vim/swaps
set undodir=$HOME/.vim/undo

" Search
set hlsearch
set ignorecase
set smartcase " Don't ignore case if searching with upper case letter
set incsearch
set wrapscan

" Scroling edge offset
set scrolloff=3
set sidescrolloff=3

" New window
set splitbelow
set splitright

" Mouse
set mouse=a
set mousefocus
set ttymouse=xterm

" Bell
set noerrorbells
set visualbell

" Spelling
set spell
set spelllang=en_ca

" Command mode completion
set wildmenu
set wildmode=list:longest

" Misc. configs
set ttyfast
syntax on
filetype plugin indent on

" Filetype associations
au BufRead,BufNewFile *.md set filetype=markdown

" Create .netrwhist in $HOME
let g:netrw_home=$HOME

" Trim trailing whitespaces
fun! <SID>StripTrailingWhitespaces()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfun
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

" Setup plugins managed by vim-plug
so ~/.vim/vimrc.plugs

" Setup key bindings
so ~/.vim/vimrc.bindings

